version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
workflows:
  test:
    jobs:
      - cypress/run
  test-record:
    jobs:
      - cypress/run:
          context: Cypress Variables
          record: true
